config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  root to: "exhibitions#index"

  resources :categories do
    collection do
      get 'search_children'
      get 'search_grandchildren'
    end
  end
  # resources :categories doに7つのアクションがないと指摘を受けました。対応をお願いします  

  resources :exhibitions do
    collection do
      get 'modal'
      get 'search'
      get 'category_children'
      get 'category_grandchildren'
      get 'search_children'
      get 'search_grandchildren'
      get 'done'
    end
    member do
      get 'buy'
      post 'pay'
    end
  end

  resources :mypage ,only: :index
  resources :logouts ,only: :index
  resources :paymethods ,only: :index
  resources :addresses ,only: :index
  resources :editmails ,only: :index
  
  resources :cards, only: [:new, :index, :show, :edit, :update] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :images ,only: :index

end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user

  belongs_to :category, optional: true

  belongs_to_active_hash :prefecture
  validates :price,                      presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: "入力してください" }
  validates :shipping_date,              presence: true
  validates :item_name,                  presence: true, length: { minimum: 1, maximum: 40, message: "入力してください" }
  validates :item_description,           presence: true, presence: true, length: { minimum: 1, maximum: 1000, message: "入力してください" }
  validates :category_id,                presence: true
  validates :item_status,                presence: true
  validates :shipping_charges,           presence: true
  validates :prefecture_id,              presence: true
  validates_associated :images,          presence: true
  validates :images,          presence: true

  enum deal: { sell: 0, SOLDOUT: 1 }

  def self.search(search)
    if search
      Exhibition.where('item_name  LIKE(?)',"%#{search}%")
                              # これがExhibitionテーブルにある該当するカラム名を引っ張ってこれる！
    else
      Exhibition.all
    end
  end
end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController

  require 'payjp'
  before_action :set_exhibition, only: [:show, :edit, :update, :buy]
  before_action :set_user, only: [:edit, :update]
  before_action :authenticate_user!, only: [:show, :edit, :update]
  before_action :set_card, only: [:buy, :pay]
  def index
    @exhibitions = Exhibition.all.includes(:user).order("created_at DESC")
    @categories = Category.roots
  end

  def new
    @categories = Category.roots
    @exhibition = Exhibition.new
    @image = @exhibition.images.new
  end
  
  def create
    @categories = Category.roots
    @exhibition = Exhibition.new(exhibition_params)
    respond_to do |format|
      if params[:exhibition][:images_attributes] != nil
        if @exhibition.save
          format.html{redirect_to modal_exhibitions_path}
        else
          flash.now[:alert] = '必須項目を入力してください。'
          @image = @exhibition.images.new
          format.html{render action: 'new'}
        end
      else
        flash.now[:alert] = '必須項目を入力してください。'
        @image = @exhibition.images.new
        format.html{render action: 'new'}
      end
    end
  end
  
  def modal
  end
  
  def search
    @exhibitions = Exhibition.search(params[:keyword])
  end

  def show
    @images = Image.where(exhibition_id: params[:id]).order("created_at DESC")
    if user_signed_in?
      @deal = Exhibition.find_by(deal: params[:deal])
      @exhibition = Exhibition.find(params[:id])
      @categories = Category.find(params[:id])
      render :show
    else
      redirect_to user_session_path method: :post
    end
    
  end
  
  def edit
    @categories = Category.roots
    @exhibition.images.new
  end
  
  def update
    @categories = Category.roots
    if @exhibition.update(exhibition_params)
      redirect_to root_path, notice: '編集が完了しました。'
    else
      @exhibition = Exhibition.find(@exhibition.id)
      flash.now[:alert] = '必須項目を入力してください。'
      render :edit
    end
  end
  
  # ---pay.jpの処理---
  def buy
    if @card.blank?
      redirect_to new_card_path
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end
  
  def pay
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    exhibition = Exhibition.find(params[:id])
    
    Payjp::Charge.create(
    amount: exhibition.price, #支払金額を入力（itemテーブル等に紐づけても良い）
    customer: @card.customer_id, #顧客ID
    currency: 'jpy', #日本円
    )
    
    exhibition.update!(deal: 1)
    redirect_to action: 'done' #完了画面に移動
  end
  # ---pay.jpの処理ここまで---

  def category_children  
    @category_children = Category.find(params[:parent]).children 
  end

  def category_grandchildren
    @category_grandchildren = Category.find(params[:child]).children
  end

  def search_children
    @categories = Category.roots
    respond_to do |format|
      format.html
      format.json {
        @children = Category.find(params[:parent_id]).children
      }
    end
  end

  def search_grandchildren
    respond_to do |format|
      format.html
      format.json {
        @grandchildren = Category.find(params[:child_id]).children
      }
    end
  end

  def destroy
    @exhibition = Exhibition.find(params[:id])
    @exhibition.destroy
    redirect_to root_path, notice: '削除が完了しました。'
  end

  def exhibition_params
    params.require(:exhibition).permit(:price,:shipping_date,:category_id,:prefecture_id,:shipping_charges,:item_description,:item_status, :item_name, :brand, images_attributes: [:image,  :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_exhibition
    @exhibition = Exhibition.find(params[:id])
  end

  def set_user
    @user = Exhibition.find_by(user_id: params[:user_id])
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/exhibitions/buy.html.haml
.buy-wrapper
  .buy-header
    = link_to root_path do
      = image_tag asset_path("logo.png"), size: "185x49"
  .buy-body
    .buy-main
      %h2.buy-main-head
        購入内容の確認
      .buy-container
        .buy-content
          .buy-item-container
            .buy-item-container__box
              .buy-item-container__box__img
                = image_tag @exhibition.images.first.image.url,size: "80x60"
              .buy-item-container__box__detail
                %p.buy-item-container__box__detail__name
                  = @exhibition.item_name
                .buy-item-container__box__detail__price
                  %span.buy-item-container__box__detail__price__number
                    %p￥
                    = @exhibition.price
                  %span.buy-item-container__box__detail__price__tax
                    （税込）送料込み
        .buy-content
          .buy-pay
            .buy-pay__box
              .buy-pay__box__container
                .buy-pay__box__container__price
                  .buy-pay__box__container__price__text
                    支払い金額
                  .buy-pay__box__container__price__right
                    %p￥
                    = @exhibition.price
                .buy-pay__box__container__check
                  .buy-pay__box__container__check__btn
                  = form_with local: true do |form|
                    = form.check_box :content, class:'check-btn'
                    %label.label
                      ポイントを使用 (所持ポイント: P0)
              .buy-pay__box__container
                .buy-pay__box__container__fee
                  %h3.buy
                    支払い方法
                  .buy-pay__box__container__fee__price
                    = link_to '変更する', cards_path, class: "buy-link__change"
                %p.buy-pay__box__container__credit
                  クレジットカード
                  %br
                    = "**** **** **** " + @default_card_information.last4
                  %br 
                    - exp_month = @default_card_information.exp_month.to_s
                    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                    = "有効期限 " + exp_month + " / " + exp_year
                .buy-pay__box__container__card
                  -# = image_tag src="https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?35314277", size: "49x15"
              .buy-pay__box__container__ship
                .buy-pay__box__container__ship__head
                  %h3.buy
                    配送先
                  .buy-pay__box__container__ship__head__price
                    = link_to '変更する', "", class: "buy-link__change"
                .buy-pay__box__container__ship__price
                  %p
                    = "〒" + current_user.address.postal_code
                    %br
                      = current_user.address.prefectures + current_user.address.municipalities + current_user.address.house_number
                    %br
                      = current_user.address.ship_family_name + current_user.address.ship_last_name
              .buy-btn
                .buy-btn__container
                  = form_tag pay_exhibition_path(@exhibition.id), local: true, method: :post
                  %button 購入する


  .sell-footer
    .sell-footer__container
      .sell-footer__container__box
        %ul.footer-ul
          %li.footer-li
            = link_to 'プライバシーポリシー', '/', class: "buy-link"
          %li.footer-li
            = link_to 'メルカリ利用規約', '/', class: "buy-link"
          %li.footer-li
            = link_to '特定商取引に関する表記', '/', class: "buy-link"
      .sell-footer__container__image
        = image_tag src="http://furima.tokyo/assets/logo-white-f61961ed5170064c5f33dd4524bdceeb5a5df2c83eb76fba31143f63fbab2c5e.svg", size: "160x46"
      .sell-footer__container__inc
        © FURIMA 

app/views/exhibitions/destroy.html.haml
.destroy.js-modal
  .destroy__bg.js-destroy-close
  .destroy__content
    .destroy__content__border
    %h2.destroy__content__head
      商品を削除しました。
    .sell-select-icon
      = link_to 'トップページにもどる', root_path, class: "modal__content__link"

app/views/exhibitions/done.html.haml
.modal.js-modal
  .modal__bg.js-modal-close
  .modal__content
    .modal__content__border
    %h2.modal__content__head
      お買い上げありがとうございました。
      
    .sell-select-icon
      = link_to 'トップページにもどる', root_path, class: "modal__content__link"

app/views/exhibitions/edit.html.haml
.sell-wrapper
  .sell-header
    = link_to root_path do
      = image_tag asset_path("logo.png"), size: "185x49"
  .sell-body
    .sell-main
      %h2.sell-main-head
        商品の情報を入力
      = form_with model:@exhibition, url: exhibition_path(@exhibition), method: :put, local: true, class: "sell-form" do |form|
        .sell-img-box
          .sell-img-box__upload
            .sell-img-box__upload__title
              出品画像
              %span.require
                必須
            .sell-img-box__upload__text
              最大10枚までアップロードできます
        #previews
          - @exhibition.images.each_with_index do |image, index|
            // コントローラーのeditで@exhibition.images.newにてインスタンス変数を定義したため、
            // @exhibition.imagesの最後にこの要素が存在している
            // 配列番号と画像枚数が一緒でない時 => テーブルの画像を表示
            // テーブルに画像が3枚あるとき、indexは0.1.2、画像要素数は最後の要素含む4-1=3となり、一致しない
            - if index != (@exhibition.images.length - 1)
              .image-wrapper{data: {index: "#{index}"}}
                = image_tag image.image.url, data: {index:index}, class: "edit-img"
                .file-remove 削除
              %input{name: "exhibition[images_attributes][#{index}][_destroy]", class: "hidden", data: {index: index}, type: "checkbox"}
          #image-input
            = form.fields_for :images, class: "form-image" do |image|
              // 配列番号と画像枚数が一緒の時 => 最後の要素のとき
              // テーブルに画像が3枚あるとき、空の番ではindexは3、画像要素数は3となり、一致
              // 最後の要素を表示（画像は空だが、新しい画像を投稿するinputタグを生成するため）
              - if image.index === (@exhibition.images.length - 1) 
                = image.label :image, class: "upload-area", for: "upload-for" do
                  .file-group{data:{index:image.index}}
                    = image.file_field :image, class: "upload-file", id: "upload-for"
                    %i.fa.fa-camera-retro#camera

        .sell-content
          .sell-name
            .sell-name__head
              .sell-name__head__text
                商品名
                %span.require
                  必須
            .sell-name__form
              = form.text_field :item_name, placeholder: "商品名（必須40文字まで）", class:'sell-form__default error-item-name'
              .must-message__item-name.error
            .sell-description
              .sell-description__head
                .sell-description__head__text
                  商品の説明
                  %span.require
                    必須
              .sell-description__form
                = form.text_area :item_description, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class:'sell-textarea-default error-item-description'
                .must-message__item-description.error
        .sell-content
          .sell-details
            .sell-details__text
              商品の詳細
            .sell-details__box
              .sell-details__box__category
                カテゴリー
                %span.require
                  必須
                .sell-select-wrap
                  .sell-select-icon
                    = form.collection_select :root_category_id, @categories, :id, :item, { prompt: "---", selected: @exhibition.category.root_id}, { class: "sell-select-default error-category", id: "category_select", required: true}
                    = icon('fas', 'chevron-down sell-select-icon__allow')
                  .must-message__category.error
                .sell-select-children
                  .must-message__category.error
              .sell-brand
                .sell-brand__head
                  .sell-brand__head__text
                    ブランド名
                    %span.require--brand
                      任意
                .sell-brand__form
                  = form.text_field :brand, placeholder: "例 )シャネル", class:'sell-form__brand'
              .sell-details__box__status
                商品の状態
                %span.require
                  必須
                .sell-select-wrap
                  .sell-select-icon
                    = form.select :item_status, [["新品、未使用"],["未使用に近い"],["目立った傷や汚れなし"]], { prompt: "選択してください" }, class:'sell-select-default error-status'
                    = icon('fas', 'chevron-down sell-select-icon__allow')
                  .must-message__status.error
        .sell-content
          .sell-ship
            .sell-ship__text
              配送について
            .sell-ship__box
              .sell-ship__box__category
                配送料の負担
                %span.require
                  必須
                .sell-select-wrap
                  .sell-select-icon
                    = form.select :shipping_charges, [["送料込み（出品者負担）"],["着払い（購入者負担）"]], { prompt: "選択してください" }, class:'sell-select-default error-shipping-charge'
                    = icon('fas', 'chevron-down sell-select-icon__allow')
                  .must-message__shipping-charge.error
              .sell-ship__box__status
                発送元の地域
                %span.require
                  必須
                .sell-select-wrap
                  .sell-select-icon
                    = form.collection_select(:prefecture_id, Prefecture.all, :id, :name, {prompt: "---"}, {class: "sell-select-default error-shipping-area"})
                    = icon('fas', 'chevron-down sell-select-icon__allow')
                  .must-message__shipping-area.error
              .sell-ship__box__status
                発送までの日数
                %span.require
                  必須
                .sell-select-wrap
                  .sell-select-icon
                    = form.select :shipping_date, [["1~2日で発送"],["2~3日で発送"],["4~7日で発送"]], { prompt: "選択してください" }, class:'sell-select-default error-shipping-date'
                    = icon('fas', 'chevron-down sell-select-icon__allow')
                  .must-message__shipping-date.error
        .sell-content
          .sell-price
            .sell-price__left
              販売価格(300〜9,999,999)
            .sell-price__box
              .sell-price__box__container
                .sell-price__box__container__text
                  価格
                  %span.require
                    必須
                .sell-price__box__container__right
                  .sell-price__box__container__right__money
                    ¥
                  .sell-price__box__container__right__select
                    .sell-select-wrap
                      = form.number_field :price, class: "sell-form__number error-price", placeholder: "0", min: 300, max: 9999999
                    .must-message__price.error
              .sell-price__box__fee
                .sell-price__box__fee__text
                  販売手数料 (10%)
                .sell-price__box__fee__tax -
              .sell-price__box__profit
                .sell-price__box__profit__text
                  販売利益
                  %span.require
                    必須
                  .price
                .sell-price__box__profit__price -
        .sell-content
          .sell-btns
            .sell-btns__text
              = link_to '禁止されている出品', '/', class: "sell-link__note"
              、
              = link_to '行為', '/', class: "sell-link__note"
              を必ずご確認ください。
              %br
              またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
              %br
              また、出品をもちまして
              = link_to '加盟店規約', '/', class: "sell-link__note"
              に同意したことになります。
            .sell-btns__btn
              .sell-select-icon
                = form.submit '編集する', class: 'sell-btns__btn__up'
              .sell-btns__btn__back
                = link_to 'もどる', exhibition_path(@exhibition), class: "sell-link__back"
  .sell-footer
    .sell-footer__container
      .sell-footer__container__box
        %ul.footer-ul
          %li.footer-li
            = link_to 'プライバシーポリシー', '/', class: "buy-link"
          %li.footer-ul
            = link_to 'FURIMA利用規約', '/', class: "buy-link"
          %li.footer-ul
            = link_to '特定商取引に関する表記', '/', class: "buy-link"
      .sell-footer__container__image
        = image_tag asset_path("logo.png"), size: "120x34"
      .sell-footer__container__inc
        © FURIMA

app/views/exhibitions/index.html.haml
.top
  = render partial: "shared/top-header", locals: { exhibition: @exhibition }
  .top-main
    .top-upper 
      .upper-contents
        .upper-contents__box
          %h2.topic-first
            人生を変えるフリマアプリ
          %h3.topic-second
            FURIMAはだれでもかんたんに出品・購入できるフリマアプリです
          .topic-items
            =link_to "#", class: "topic-items__App", size: '180x53' do
              = image_tag asset_path("app-store.svg"),size: '180x53'
            =link_to "#",class: "topic-items__Google", size: '180x53' do
              = image_tag asset_path("google-play.svg"),size: '180x53'
    .top-content-text
      %h2.top-introduction
        FURIMAが選ばれる3つの理由
      .top-content-imageBox
        %ul.lists-imageBox
          %li.listOnly-imageBox
            .listOnly-imageBox__image
              %span.number-one 1
              = image_tag asset_path("pict-reason-01"), size: "306x306"
            %h3.listOnly-imageBox__body
              %span 3分
              ですぐに出品
            %p.picUp-text
              スマホで入力するだけで簡単に出品できる！
          %li.listOnly-imageBox
            .listOnly-imageBox__image
              %span.number-one 2
              = image_tag asset_path("pict-reason-02"), size: "306x306"
            %h3.listOnly-imageBox__body
              %span シンプル
              で使いやすい
            %p.picUp-text
              めんどくさい入力は必要なく、検索も購入もスムーズ！
          %li.listOnly-imageBox
            .listOnly-imageBox__image
              %span.number-one 3
              = image_tag asset_path("pict-reason-03"), size: "306x306"
            %h3.listOnly-imageBox__body
              手数料
              %span 業界最安
            %p.picUp-text
              最大3%でお得に出品&購入！
    .main-imageBox
      .main-imageBox__backgroundImage
        .backgroundImage-contents
          .backgroundImage-contents__box
            %h2.topic-first-2
              会員数日本一位
            %h3.topic-second-2
              FURIMAは、フリマアプリで最も人気。
            %h4.topic-second-2
              出品・購入回数も業界最多です！
            %h5.topic-second-2
              ほしかったあの商品に出会えるかもしれません。
            .topic-items-2
              =link_to "#", class: "topic-items-2__App", size: '180x53' do
                = image_tag asset_path("app-store"), size: '180x53'
              =link_to "#",class: "topic-items-2__Google", size: '180x53' do
                = image_tag asset_path("google-play"), size: '180x53'
    .top-content-text
      %h2.top-introduction
        FURIMAの特徴
      .top-content-imageBox
        %ul.lists-imageBox
          %li.listOnly-imageBox
            .listOnly-imageBox__image
              %span.number-one 1
              = image_tag asset_path("icon-01.png"), size: "219x337"
            %h3.listOnly-imageBox__bodySecond
              %span 
              簡単に売り買いできる
            %p.picUp-text
              スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
          %li.listOnly-imageBox
            .listOnly-imageBox__image
              %span.number-one 2
              = image_tag asset_path("icon-03.png"), size: "219x337"
            %h3.listOnly-imageBox__bodySecond
              %span
              売上金は即日振込みに対応
            %p.picUp-text
              午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
          %li.listOnly-imageBox
            .listOnly-imageBox__image
              %span.number-one 3
              = image_tag asset_path("icon-04.png"), size: "219x337"
            %h3.listOnly-imageBox__bodySecond
              様々な支払いに対応
              %span 
            %p.picUp-text
              お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
    .span-box
    .top-item-contents
      .top-item-contents__infomation
        %h2.picup-category
          ピックアップカテゴリー
        .categoryBox
          .categoryHead
            = link_to "#" do
              %h3.category-text 新規投稿商品
          .categoryList
            - @exhibitions.each do |exhibition|
              .categoryList__exhibition
                = link_to exhibition_path(exhibition), class: 'link-showpage', method: :get do
                  .categoryList__exhibition__image
                    - if exhibition.deal == "SOLDOUT"
                      = image_tag asset_path("sold_out.png"), size: "220x130", class: "sold-out"
                    = image_tag("#{exhibition.images.first.image}", size: "230x230", class: 'image-top')
                  .categoryList__exhibition__body
                    .exhibition-item-name
                      = exhibition.item_name
                    .exhibition-price
                      .exhibition-price__box
                        = exhibition.price 
                        %span 円
                      .exhibition-icon
                        %i.fas.fa-star
                        %p.star-count 0
                    %h3.tax-include
                      (税込)
    .span-box-second
    .appFooter
      .appFooter__box
        %h2.banner-text
          だれでもかんたん、人生を変えるフリマアプリ
        %p.banner-body
          今すぐ無料ダウンロード！
        .appFooter-icon
          =link_to "#", class: "appFooter-icon__App", size: '180x53' do
            = image_tag asset_path("app-store"), size: '180x53'
          =link_to "#",class: "appFooter-icon__Google", size: '180x53' do
            = image_tag asset_path("google-play"), size: '180x53'
    = render "shared/top-footer"
  = render "shared/sell_page_box"

app/views/exhibitions/modal.html.haml
.modal.js-modal
  .modal__bg.js-modal-close
  .modal__content
    .modal__content__border
    %h2.modal__content__head
      出品が完了しました。
    .sell-select-icon
      = link_to '続けて出品する', new_exhibition_path, class: "sell-link__continue"
      = link_to 'トップページにもどる', root_path, class: "modal__content__link"

app/views/exhibitions/search_children.html.haml
.category
  .category__wrapper
    %i.fas.fa-list-ul.category__wrapper__icon
    %p.category__wrapper__target カテゴリから探す
    .category__wrapper__flex
      .category__wrapper__flex__parents
        - @categories.each do |category|
          = link_to "#", class: "category__wrapper__flex__parents__item" do
            .category__wrapper__flex__parents__item__text{"data-item-id": category.id}
              #{category.item}
      .category__wrapper__flex__children
      .category__wrapper__flex__grandchildren

  .category__brand  
    %i.fas.fa-tag.category__brand__icon
    %p.category__brand__target ブランドから探す
    %ul.category__brand__navi  
      = link_to "#", class: "category__brand__navi__item" do
        %li.category__brand__navi__item__text{"data-brand-id": "1"}
          シャネル
      = link_to "#", class: "category__brand__navi__item" do
        %li.category__brand__navi__item__text{"data-brand-id": "2"}
          ナイキ
      = link_to "#", class: "category__brand__navi__item" do
        %li.category__brand__navi__item__text{"data-brand-id": "3"}
          ルイ ヴィトン        
      = link_to "#", class: "category__brand__navi__item" do
        %li.category__brand__navi__item__text{"data-brand-id": "4"}
          シュプリーム
      = link_to "#", class: "category__brand__navi__item" do
        %li.category__brand__navi__item__text{"data-brand-id": "5"}
          アディダス
      = link_to "#", class: "category__brand__navi__item" do
        %li.category__brand__navi__item__text{"data-brand-id": "6"}
          ブランド一覧

app/views/exhibitions/show.html.haml
.exhead
  %ul
    %li
      %a{:href => "/"} FURIMA
    %li
      %i.fa.fa-angle-right
    %li
      %a{:href => "#"} ベビー・キッズ
    %li
      %i.fa.fa-angle-right
    %li
      %a{:href => "#"} ベビー服(男女兼用)  ~95cm
    %li
      %i.fa.fa-angle-right
    %li
      %a{:href => "#"} アウター
    %li
      %i.fa.fa-angle-right
    %li
      %p product3

.exmain
  .exmain__top
    .ex-content
      .show-box
        %h2.show-box__name
          = @exhibition.item_name
        .show-box__body
          %ul.main__show__content__top__itemInfo__image__ul
            - @exhibition.images.each_with_index do |image, i|
              = image_tag image.image.url,class:"main__show__content__top__itemInfo__image__ul__li__top"
            - if @exhibition.deal == "SOLDOUT"
              = image_tag asset_path("sold_out.png"), size: "220x130", class: "sold-out"
        .show-box__foot 
          %ul
            %li 
            - objects = @exhibition.images
            - objects.each do |object|
              %li.main__show__content__top__itemInfo__image__ul__li
                = image_tag object.image.url
        .show-price
          .show-price__number
            %i.fa.fa-yen-sign
              = @exhibition.price
          .show-price__tax
            %span (税込)
          .show-price__shipping
            %span 送料込み
        .show-buy-btn 
        - if user_signed_in? && @exhibition.user_id != current_user.id
          - if @exhibition.deal == "SOLDOUT"
            = link_to "売り切れました トップへ戻る", root_path
          - else
            = link_to "購入画面に進む", buy_exhibition_path(@exhibition), class: "show-buy-btn__buy"
        .show-exbox
          = @exhibition.item_description
        .show-table
          %table
            %tbody
              %tr
                %th 出品者
                %td 
                  = @exhibition.user.nickname
              %tr
                %th カテゴリー
                %td
                  =link_to "#{@exhibition.category.root.item}", "#"
                  =link_to ">#{@exhibition.category.parent.item}", "#"
                  =link_to ">#{@exhibition.category.item}","#"
              %tr
                %th ブランド
                %td
                  = @exhibition.brand
              %tr
                %th 商品の状態
                %td 
                  = @exhibition.item_status
              %tr
                %th 配送料の負担
                %td 
                  = @exhibition.shipping_charges
              %tr
                %th 発送元の地域
                %td
                  = @exhibition.prefecture.name
              %tr
                %th 発送日の目安
                %td 
                  = @exhibition.shipping_date
        .option-table
          %ul
            %li
              #like-btn.option-btn.like-btn
                %i.fa.fa-star
                お気に入り 0
          %ul.report-btn
            %li.report-btn__box
              %a{:href => "#"} 
                %i.fa.fa-flag
                不適切な商品の通報
        .show-user-btn
          - if user_signed_in? && @exhibition.user_id == current_user.id
            = link_to "編集画面に進む", edit_exhibition_path(@exhibition), class: "show-user-btn__edit"
            = link_to "商品削除", exhibition_path(@exhibition), method: :delete, class: "show-user-btn__delete"
          - unless user_signed_in?
            = link_to "ログイン画面へ", new_user_session_path, class: "show-buy-btn__buy"
      .excomment-box
        %textarea#comment_body{:name => "comment[body]", :required => "required"}
        %p.message
          相手のことを考え丁寧なコメントを心がけましょう。
          %br/
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %br/
        %button.comment-btn{:name => "button", :type => "submit"}
          %i.fa.fa-comment
          コメントする

      %ul.exlinks
        %li
          %a{:href => "#"}
            %i.fa.fa-angle-left
            %span
            前の商品
        %li
          %a{:href => "#"}
            %span 
            後ろの商品
            %i.fa.fa-angle-right
      .exrelated
        %a{:href => "#"}ベビーキッズをもっと見る  