config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  root to: "exhibitions#index"

  resources :categories do
    collection do
      get 'search_children'
      get 'search_grandchildren'
    end
  end
  # resources :categories doに7つのアクションがないと指摘を受けました。対応をお願いします  

  resources :exhibitions do
    collection do
      get 'modal'
      get 'search'
      get 'category_children'
      get 'category_grandchildren'
      get 'search_children'
      get 'search_grandchildren'
      get 'done'
    end
    member do
      get 'buy'
      post 'pay'
    end
  end

  resources :mypage ,only: :index
  resources :logouts ,only: :index
  resources :paymethods ,only: :index
  resources :addresses ,only: :index
  resources :editmails ,only: :index
  
  resources :cards, only: [:new, :index, :show, :edit, :update] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :images ,only: :index

end

app/models/address.rb
class Address < ApplicationRecord
  validates :ship_family_name, presence: true,
  format: {
    with: /[^ -~｡-ﾟ]+/,
    message: "全角のみで入力して下さい"
  }
  validates :ship_last_name, presence: true,
  format: {
    with: /[^ -~｡-ﾟ]+/,
    message: "全角のみで入力して下さい"
  }
  validates :ship_j_family_name, presence: true,
  format: {
    with: /[^ -~｡-ﾟ]+/,
    message: "全角のみで入力して下さい"
  }
  validates :ship_j_last_name, presence: true,
  format: {
    with: /[^ -~｡-ﾟ]+/,
    message: "全角のみで入力して下さい"
  }
  validates :postal_code, presence: true
  validates :prefectures, presence: true
  validates :municipalities, presence: true
  validates :house_number, presence: true
  belongs_to :user, inverse_of: :address

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :exhibitions
end

app/models/exhibition.rb
class Exhibition < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user

  belongs_to :category, optional: true

  belongs_to_active_hash :prefecture
  validates :price,                      presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: "入力してください" }
  validates :shipping_date,              presence: true
  validates :item_name,                  presence: true, length: { minimum: 1, maximum: 40, message: "入力してください" }
  validates :item_description,           presence: true, presence: true, length: { minimum: 1, maximum: 1000, message: "入力してください" }
  validates :category_id,                presence: true
  validates :item_status,                presence: true
  validates :shipping_charges,           presence: true
  validates :prefecture_id,              presence: true
  validates_associated :images,          presence: true
  validates :images,          presence: true

  enum deal: { sell: 0, SOLDOUT: 1 }

  def self.search(search)
    if search
      Exhibition.where('item_name  LIKE(?)',"%#{search}%")
                              # これがExhibitionテーブルにある該当するカラム名を引っ張ってこれる！
    else
      Exhibition.all
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :exhibition
  # validates :image,          presence: true
  # まだ挙動確認中のため残しておく
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, {presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }}
  validates :family_name, presence: true,
            format: {
              with: /[^ -~｡-ﾟ]+/,
              message: "全角のみで入力して下さい"
            }
  validates :last_name, presence: true,
            format: {
              with: /[^ -~｡-ﾟ]+/,
              message: "全角のみで入力して下さい"
            }
  validates :j_family_name, presence: true,
            format: {
              with: /[^ -~｡-ﾟ]+/,
              message: "全角のみで入力して下さい"
            }
  validates :j_last_name, presence: true,
            format: {
              with: /[^ -~｡-ﾟ]+/,
              message: "全角のみで入力して下さい"
            }
  validates :birth_year, presence: true
  validates :birth_month, presence: true
  validates :birth_day, presence: true
  has_one :address, inverse_of: :user
  accepts_nested_attributes_for :address
  has_many :cards
  has_many :exibitions
  has_one :purchase
end

app/controllers/buy_controller.rb
class BuyController < ApplicationController
  def index
    
  end

  def show
    
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_helper.rb
module BuyHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/editmails_helper.rb
module EditmailsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/logouts_helper.rb
module LogoutsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/paymethods_helper.rb
module PaymethodsHelper
end

app/helpers/sell_helper.rb
module SellHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", name: "viewport"}
    %title FreemarketSample68e
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    %title FreemarketSample68e
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    .notifications
    - flash.each do |key, value|
      = content_tag(:div, value, class: key)
  %body
    = yield

app/views/shared/_error_messages.html.haml
- if model.errors.any?
  .alert.alert-warning
    %ul
      - model.errors.full_messages.each do |message|
        %li= message

app/views/shared/_mypage_flex_left.html.haml
-# = render "shared/mypage_flex_left"で呼び出せます
.mypage__flex__left
  .mypage__flex__left__list{"data-mypage" => "-1"}
    = link_to mypage_index_path, class: "mypage__flex__left__list__link" do
      %p マイページ
      .mypage-icon-1
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-2"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p やることリスト
      .mypage-icon-2
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-3"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p いいね！一覧
      .mypage-icon-3
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-4"}
    = link_to new_exhibition_path, class: "mypage__flex__left__list__link" do
      %p 出品する
      .mypage-icon-4
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-5"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p 出品した商品-出品中
      .mypage-icon-5
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-6"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p 出品した商品-取引中
      .mypage-icon-6
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-7"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p 出品した商品-売却済
      .mypage-icon-7
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-8"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p 購入した商品-取引中
      .mypage-icon-8
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-9"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p 購入した商品-過去の取引
      .mypage-icon-9
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-10"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p ニュース一覧
      .mypage-icon-10
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-11"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p 評価一覧
      .mypage-icon-11
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-12"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p ガイド
      .mypage-icon-12
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-13"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p お問い合わせ
      .mypage-icon-13
        = icon('fas', 'chevron-right' )
        
  %h3.mypage-left-list-title メルペイ
  .mypage__flex__left__list{"data-mypage" => "-14"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p 売上・振込申請
      .mypage-icon-14
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-15"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p ポイント
      .mypage-icon-15
        = icon('fas', 'chevron-right' )

  %h3.mypage-left-list-title  設定
  .mypage__flex__left__list{"data-mypage" => "-16"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p プロフィール
      .mypage-icon-16
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-17"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p 発送元・お届け先住所変更
      .mypage-icon-17
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-18"}
    = link_to "/cards", method: :get, class: "mypage__flex__left__list__link" do
      %p 支払い方法
      .mypage-icon-18
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-19"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p メール/パスワード
      .mypage-icon-19
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-20"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p 本人情報
      .mypage-icon-20
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-21"}
    = link_to "#", class: "mypage__flex__left__list__link" do
      %p 電話番号の確認
      .mypage-icon-21
        = icon('fas', 'chevron-right' )
  .mypage__flex__left__list{"data-mypage" => "-22"}
    = link_to destroy_user_session_path, method: :delete, class: "mypage__flex__left__list__link" do
      %p ログアウト
      .mypage-icon-22
        = icon('fas', 'chevron-right' )

app/views/shared/_sell_page_box.html.haml
-# = render "shared/sell_page_box"で呼び出し
.top__sell-page
  - if user_signed_in?
    = link_to new_exhibition_path, class:' top__sell-page__link' do
      .camera-content
        %p.purchase-text
          出品する
        = image_tag asset_path("icon_camera.png"),size:"54x54",class:'camera-content__icon'
  - else
    = link_to new_user_session_path, class:' top__sell-page__link' do
      .camera-content
        %p.purchase-text
          出品する
        = image_tag asset_path("icon_camera.png"),size:"54x54",class:'camera-content__icon'

app/views/shared/_top-footer.html.haml
.top-footer-box
  .top-footer
    .footer-top-content
    .footer-contents
      .footer-box
        FURIMAについて
        .box-link
          = link_to "#", class: "aaa" do
            会社概要 （運営会社）
        .box-link
          = link_to "#", class: "aaa" do
            プライバシー
        .box-link
          = link_to "#", class: "aaa" do
            FURIMA利用規約
        .box-link
          = link_to "#", class: "aaa" do
            ポイントに関する特約
      .footer-box
        FURIMAを観る
        .box-link
          = link_to "#", class: "aaa" do
            カテゴリー一覧
        .box-link
          = link_to "#", class: "aaa" do
            ブランド一覧
      .footer-box
        ヘルプ＆ガイド
        .box-link
          = link_to "#", class: "aaa" do
            FURIMAガイド
        .box-link
          = link_to "#", class: "aaa" do
            FURIMAロゴ利用ガイドライン
        .box-link
          = link_to "#", class: "aaa" do
            お知らせ
    .footer-icon-box
      .footer-icon
        = image_tag src ="http://furima.tokyo/assets/logo-white-f61961ed5170064c5f33dd4524bdceeb5a5df2c83eb76fba31143f63fbab2c5e.svg"
      .footer-second-icon
        &#169;FURIMA

app/views/shared/_top-header.html.haml
.top__header
  .top__header__home
    .top__header__home__wrapper
      .top__header__home__wrapper__logo
        = image_tag asset_path("logo.png"),id: "top__header--logo"
      .top__header__home__wrapper__search
        = form_with  model: @exhibition, url: "#", local: true, method: :get, class: "new-message" do |form|
          = form.text_field :keyword, placeholder: "キーワードから探す", class: "search-box" 
          %button{type: "submit", placeholder: "キーワードから探す",class: "search-btn" } 
            %i.fas.fa-search
  .top__header__item
    .top__header__item__type
      .top__header__item__type__category
        .top__header__item__type__category__wrapper
          %i.fas.fa-list-ul.top__header__item__type__category__wrapper__icon
          %p.top__header__item__type__category__wrapper__target カテゴリ
          .top__header__item__type__category__wrapper__flex
            .top__header__item__type__category__wrapper__flex__parents#parents
              - @categories.each do |category|
                = link_to "#", class: "top__header__item__type__category__wrapper__flex__parents__item",id:"parents-item" do
                  .top__header__item__type__category__wrapper__flex__parents__item__text#parents-text{"data-item-id": category.id}
                    #{category.item}
            .top__header__item__type__category__wrapper__flex__children#children
            .top__header__item__type__category__wrapper__flex__grandchildren#grandchildren
      .top__header__item__type__brand  
        %i.fas.fa-tag.top__header__item__type__brand__icon
        %p.top__header__item__type__brand__target ブランド
        %ul.top__header__item__type__brand__navi  
          = link_to "#", class: "top__header__item__type__brand__navi__item" do
            %li.top__header__item__type__brand__navi__item__text{"data-brand-id": "1"}
              シャネル
          = link_to "#", class: "top__header__item__type__brand__navi__item" do
            %li.top__header__item__type__brand__navi__item__text{"data-brand-id": "2"}
              ナイキ
          = link_to "#", class: "top__header__item__type__brand__navi__item" do
            %li.top__header__item__type__brand__navi__item__text{"data-brand-id": "3"}
              ルイ ヴィトン        
          = link_to "#", class: "top__header__item__type__brand__navi__item" do
            %li.top__header__item__type__brand__navi__item__text{"data-brand-id": "4"}
              シュプリーム
          = link_to "#", class: "top__header__item__type__brand__navi__item" do
            %li.top__header__item__type__brand__navi__item__text{"data-brand-id": "5"}
              アディダス
          = link_to "#", class: "top__header__item__type__brand__navi__item" do
            %li.top__header__item__type__brand__navi__item__text{"data-brand-id": "6"}
              ブランド一覧
    .top__header__item__user-function
      - if user_signed_in?
        .top__header__item__user-function__my-page
          = link_to "マイページ", mypage_index_path, method: :get,class:"top__header__item__user-function__my-page__text"
        .top__header__item__user-function__log-out
          = link_to "ログアウト", destroy_user_session_path, method: :delete,class:"top__header__item__user-function__log-out__text"
      - else
        .top__header__item__user-function__new-user
          = link_to "新規登録", new_user_registration_path,class:"top__header__item__user-function__new-user__text"
        .top__header__item__user-function__log-in
          = link_to "ログイン", new_user_session_path,class:"top__header__item__user-function__log-in__text"