config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  root to: "exhibitions#index"

  resources :categories do
    collection do
      get 'search_children'
      get 'search_grandchildren'
    end
  end
  # resources :categories doに7つのアクションがないと指摘を受けました。対応をお願いします  

  resources :exhibitions do
    collection do
      get 'modal'
      get 'search'
      get 'category_children'
      get 'category_grandchildren'
      get 'search_children'
      get 'search_grandchildren'
      get 'done'
    end
    member do
      get 'buy'
      post 'pay'
    end
  end

  resources :mypage ,only: :index
  resources :logouts ,only: :index
  resources :paymethods ,only: :index
  resources :addresses ,only: :index
  resources :editmails ,only: :index
  
  resources :cards, only: [:new, :index, :show, :edit, :update] do
    collection do
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  resources :images ,only: :index

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  require "payjp"
  before_action :set_card, only: [:index, :new, :delete]
  

  def index
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def new
    # ここはクレジットカード入力情報のところ
    # redirect_to action: "show" if card.exists?
    # showはindexに統合されたため記入したコードを残しておきたいため
    # 残しておく
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "index"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    if @card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to action: "new"
  end

  private

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end
  # def show #Cardのデータpayjpに送り情報を取り出します
  # 現在showページはindexに統合チームの把握のため一応残しておく
  #   card = Card.where(user_id: current_user.id).first
  #   if card.blank?
  #     redirect_to action: "new" 
  #   else
  #     Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
  #     customer = Payjp::Customer.retrieve(card.customer_id)
  #     @default_card_information = customer.cards.retrieve(card.card_id)
  #   end
  # end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/create.html.haml
config/secrets.ymlをgignoneの最下層にいれる

app/views/cards/index.html.haml
.card-wrapper
  .card-header 
    = link_to root_path do
      = image_tag "logo.png",size:'185x49'
  .card-body
    .mypage__flex__left
      = render "shared/mypage_flex_left"
    .card-contents-registration
      .card-head-registration
        登録クレジットカード情報
      .card-registration
        .card-registration__infomation
          .card-registration__infomation__card-number
            = "**** **** **** " + @default_card_information.last4
          .card-details-registration__infomation__limit-day
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
        = form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm", class: "card-delete") do
          %input{ type: "hidden", name: "card_id", value: "",class: "card-delete__button" }
          %button.card-delete__button 削除する
      - if @default_card_information
        .card-submit-box
          登録は一枚のみです。削除後 再登録ページへ移行します。
      - else
        .card-submit-box
          = link_to "クレジットカードを登録する", new_card_path, method: :get, id: "token_submit"
.top  
  .top-footer-box    
    .top-footer
      = render "shared/top-footer"

app/views/cards/new.html.haml
.card-wrapper
  .card-header
    = link_to root_path do
      = image_tag "logo.png",size:'185x49'
  .card-body
    = render "shared/mypage_flex_left"
    .card-contents
      .card-head
        クレジットカード情報入力
      .card-details
        .form-group
          = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
            %label.card-details-document カード番号
            %label.priority 必須 
            .card-input
              = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
              %br
            .card-blands
              .card-image
                = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/visa.svg?35314277', size: '49x25'
              .card-image
                = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?35314277', size: '34x20'
              .card-image
                = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?35314277', size: '30x20'
              .card-image
                = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?35314277', size: '32x20'
              .card-image
                = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?35314277', size: '21x20'
              .card-image
                = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?35314277', size: '32x20'
              .card-image
                = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/card/discover.svg?35314277', size: '32x20'
            .card-limit
              %label.card-details-document 有効期限
              %label.priority 必須
            .input-card-date
              .input-card-date__month
                %select#exp_month{name: "exp_month", type: "text"}
                  %option{value: ""} --
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                %span.input-card-between 月
              .input-card-date__year
                %select#exp_year{name: "exp_year", type: "text"}
                  %option{value: ""} --
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                %span.input-card-between  年
                %br
            .security-box
              %label.card-details-document セキュリティコード
              %label.priority 必須
            = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
            .why-card-backnumber
              .why-card-backnumber__text
                %span.question
                  ?
                %p.question-body カード裏面の番号とは？
              .card-description
                .card-description__text
                  カードの裏面をご参照ください
                = image_tag 'https://www-mercari-jp.akamaized.net/assets/img/signup/seq-card.png?35314277',size: '240x105'
            #card_token
            = submit_tag "登録する", id: "token_submit"
= render "shared/top-footer"